services:
  rust:
    image: rust:alpine3.22  
    # command: tail -f /dev/null  
    working_dir: /opt
    volumes:
      - ./:/opt  # Bind mount everything in current directory to /opt
    entrypoint: ["/bin/sh", "-c",  "sh /opt/scripts/generate_symlinks.sh && cargo test"]